var regionMap = {
  "lutsk": "Луцьк",
  "rivne": "Рівне",
  "lviv": "Львів",
  "ternopil": "Тернопіль",
  "ivano-frankivsk": "Івано-Франківськ",
  "uzhgorod": "Ужгород",
  "chernivtsi": "Чернівці",
  "khmelnitskiy": "Хмельницький",
  "zhytomir": "Житомир",
  "vinnytsia": "Вінниця",
  "cherkasy": "Черкаси",
  "kyiv": "Київ",
  "chernigiv": "Чернігів",
  "sumy": "Суми",
  "poltava": "Полтава",
  "kropyvnitskiy": "Кропивницький",
  "mykolaiv": "Миколаїв",
  "odessa": "Одеса",
  "kherson": "Херсон",
  "sympheropol": "Сімферополь",
  "zaporizhzhya": "Запоріжжя",
  "dnipro": "Дніпро",
  "kharkiv": "Харків",
  "luhansk": "Луганськ",
  "donetsk": "Донецьк",
};